### PR TITLE
chore: Add license

### LINKED ISSUE #4: Add license
If you don't include a License file, the default is that your project is protected and may not be copied.

So add `LICENSE` file on GitHub will help you choose.

MIT and Unlicense (no restrictions) are common choices.

### PR DESCRIPTION
**Pull request by MichaelCurrin**
Fixes #4 

I added to README.md as well following a pattern from my own projects. Generated with https://michaelcurrin.github.io/badge-generator/#/repo

I also fixed up headings - you should only have one H1 heading on page (markdown or HTML). So I made the others H2.

### CODE REVIEW

**Comment by MichaelCurrin** [comment]
If you prefer:

`2020 - 2021`

Then in future:

`2020 - 2022`

You're meant to put the years as they years the project was worked on. You could have a break I guess e.g. `2015 - 2018, 2020 - 2021`.

Only core maintainers I think get mentioned in license file as owners of the code - most contributors don't get added to license I don't think but get mentioned elsewhere, as you do (I added all-contributors bot to my own project too :) )

**Comment by atapas** [comment]
> You're meant to put the years as they years the project was worked on. You could have a break I guess e.g. `2015 - 2018, 2020 - 2021`.

Yes this is a good idea. Where to mention this? Will you capture this?

> Only core maintainers I think get mentioned in license file as owners of the code - most contributors don't get added to license I don't think but get mentioned elsewhere, as you do (I added all-contributors bot to my own project too :) )

Sure right. Very cool.

**Comment by MichaelCurrin** [comment]
> Yes this is a good idea. Where to mention this? Will you capture this?

Make a note somewhere for your own notes - it applies across projects.

I like to have `docs/development.md` file for notes for myself and other developers. You could add it there. Or you can make a single reference like a new repo which has that kind of info like style and developer guidelines across your repos. Then you write it once and then link to it. That only matters if you want to save writing that info in each repo.

**Comment by MichaelCurrin** [comment]
I made it a range now `2020 - 2021` so you only have to update on character every year.

**Review by atapas — APPROVED** [review]
Changes are looking good. LGTM

**Pull request merged**
